# Generated by Django 6.0.1 on 2026-01-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_google_book_id_alter_book_preview_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_ebook',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='web_reader_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, default='Technical Author', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(default='Technology', max_length=100),
        ),
    ]
